function [trm_lag_char_tot,trm_chsn_nl,X_main_org,unq_nl_comb] = generate_nl_reg_AR_NFIR(nl_ord_max,X_main_lin,X_main_org,n_lin_trms,n_lin_trms_org,trm_lag_char_lin_incld,trm_lag_char_tot,nl_ord_AR,nl_ord_NFIR)

%Generates the candidate term dictionary of an AR-NFIR NARX model. The full
%NARX dictionary is generated by generate_nl_reg, from which the nonlinear
%cross-terms between the input- and output-lagged terms are then removed.
%nl_ord_max is to be set to max(nl_ord_AR,nl_ord_NFIR). unq_nl_comb is
%returned unpruned, as it describes the superset of nonlinear combinations
%that the model simulation functions rebuild.

[trm_lag_char_tot,trm_chsn_nl,X_main_org,unq_nl_comb] = generate_nl_reg(nl_ord_max,X_main_lin,X_main_org,n_lin_trms,n_lin_trms_org,trm_lag_char_lin_incld,...
    trm_lag_char_tot); % Full NARX candidate dictionary

[trm_lag_char_tot,trm_chsn_nl,X_main_org] = rm_crs_trms_AR_NFIR(trm_lag_char_tot,trm_chsn_nl,X_main_org,...
    nl_ord_AR,nl_ord_NFIR); % Restrict the dictionary to the AR-NFIR model class

end
